require("prototypes.colonists.colonists")
require("prototypes.colonists.clone_duplicator")
require("prototypes.colonists.comsdish")
require("prototypes.colonists.landingsite")
require("prototypes.colonists.resources")
